/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("io.freefair.lombok") version "8.6"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    //testImplementation("junit:junit:4.13.2")

    testImplementation(libs.junit)
    testImplementation(libs.junitJupiterEngine)
    testImplementation(libs.mockitoCore)
//    testImplementation(platform("org.junit:junit-bom:5.11.0"))
//    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")

    //testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.theMovieDbApi)
    implementation(libs.slf4jlog4j12)
    implementation(libs.guava)
    implementation(libs.lombok)
    implementation(libs.json)
    implementation(libs.jacksonDatabind)
    implementation(libs.apacheCommonsLang)
    implementation(libs.apacheCommonsText)
    implementation(libs.apacheCommonsValidator)

    // This dependency is used by the application.
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("gazpacho.App")
}