/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("io.freefair.lombok") version "8.6"
//    id("io.quarkus")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    //testImplementation("junit:junit:4.13.2")

    testImplementation(libs.junit)
    testImplementation(libs.junitJupiterEngine)
    testImplementation(libs.mockitoCore)
    testImplementation(libs.h2Database)
//    testImplementation(platform("org.junit:junit-bom:5.11.0"))
//    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")

    //testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.theMovieDbApi)
    implementation(libs.slf4jlog4j12)
    implementation(libs.log4jApi)
    implementation(libs.log4jCore)
    implementation(libs.guava)
    implementation(libs.lombok)
    implementation(libs.json)
    implementation(libs.jsoup)
    implementation(libs.jacksonDatabind)
    implementation(libs.jacksonGuava)
    implementation(libs.apacheCommonsLang)
    implementation(libs.apacheCommonsText)
    implementation(libs.apacheCommonsValidator)
    implementation(libs.apacheCommonsCollections)
    implementation(libs.apacheHttpClient)
    implementation(libs.apacheHttpCore)
    implementation(libs.plexApi)

    implementation(libs.seleniumJava)
    implementation(libs.seleniumFirefoxWebdriver)

    implementation(libs.pgJDBC)
    implementation(libs.hibernateOrm)
    //implementation(libs.hibernateValidator)
    implementation(libs.glassfishJakartaExpressionLanguage)
    implementation(libs.hibernateAgroal)
    implementation(libs.agroalPool)
    implementation(libs.telegramBots)

//    implementation(libs.quarkusContainerImageDocker)
//    implementation(libs.quarkusRest)
//    implementation(libs.quarkusRestJackson)
//    implementation(libs.quarkusArc)
//    implementation(libs.quarkusJunit)
//    implementation(libs.restAssured)
//    implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))

    annotationProcessor(libs.hibernateProcessor)

    // This dependency is used by the application.
}

//group = "org.gazpacho"
//version = "1.0.0-SNAPSHOT"

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("gazpacho.App")
}

/*
sourceSets {
    main {
        java.srcDirs("build/generated/sources/annotationProcessor/java/main")
    }
}
*/